### ISSUE TITLE
Gps.h: No such file or directory

### ISSUE THREAD

**Issue by komms** [dalmirdasilva/ArduinoNazaDecoder#1]
Hi Dalmirdasilva,
The following error is being displayed when I'm trying to compile the code into Arduino Mega. As I'm a rookie, I don' have any idea of this file and what it does? Are there any other sources for that header file?

**Comment by dalmirdasilva** [comment]
Hi,

This lib depends on Depends on https://github.com/dalmirdasilva/ArduinoGps.

You will have to install ArduinoGps first.

Thanks!

**Comment by komms** [comment]
Thank you :)
